#include "arduino_secrets.h"

/*
  Arduino IoT Cloud Demo - BME280/VEML6030
  SparkFun Electronics
  Date: 2023/06/22
  License: MIT.

  This example demonstrates basic sensor capture and transmission to the Arduino IoT Cloud.
  
  Feel like supporting open source hardware?
  Buy a board from SparkFun!
  `--- SparkFun Arduino Uno R4 WiFi Qwiic Kit (https://www.sparkfun.com/products/22641)

  Hardware Connections:
  Plug the BME280 and VEML6030 qwiic boards into the Arduino R4 Wifi via the Qwiic connector.
*/

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Demo"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudTemperatureSensor tempC;
  CloudIlluminance luxVal;
  CloudRelativeHumidity humidityRH;
  CloudPressure pressurePa;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Wire.h>
#include <SparkFunBME280.h>
#include <SparkFun_VEML6030_Ambient_Light_Sensor.h>

#define AL_ADDR 0x48

BME280 myBME280Sensor;
SparkFun_Ambient_Light myLightSensor(AL_ADDR);

// BME280 initialization
BME280_SensorMeasurements myBME280Measures;

// Ambient Light Sensor initialization
float gain = 0.125;
int8_t integTime = 100;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  Wire.begin();
  
  // BME280 Begin
  if (!myBME280Sensor.beginI2C())
  {
    Serial.println(F("The BME280 did not respond. Please check wiring. Spinning..."));
    while(1);
  }
  
  // Ambient Light Sensor Begin
  if (!myLightSensor.begin())
  {
    Serial.println(F("The Ambient Light Sensor did not respond. Please check wiring. Spinning..."));
    while(1);
  }
  
  myLightSensor.setGain(gain);
  myLightSensor.setIntegTime(integTime);
  
  Serial.println(F("Reading settings from ambient light sensor..."));
  Serial.print(F("Gain: "));
  Serial.print(myLightSensor.readGain(), 3);
  Serial.print(F(" Integration Time: "));
  Serial.println(myLightSensor.readIntegTime());
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  // BME280 Update
  myBME280Sensor.readAllMeasurements(&myBME280Measures);
  tempC = myBME280Measures.temperature;
  humidityRH = myBME280Measures.humidity;
  pressurePa = myBME280Measures.pressure;
  
  // Ambient Light Update
  luxVal = myLightSensor.readLight();
  
}






