#include "arduino_secrets.h"

/*
  Arduino IoT Cloud Demo - BMEA400
  SparkFun Electronics
  Date: 2023/06/22
  License: MIT.

  This example demonstrates basic sensor capture and transmission to the Arduino IoT Cloud.
  
  Feel like supporting open source hardware?
  Buy a board from SparkFun!
  `--- SparkFun Arduino Uno R4 WiFi Qwiic Kit (https://www.sparkfun.com/products/22641)

  Hardware Connections:
  Plug the BMA400 qwiic board into the Arduino R4 Wifi via the Qwiic connector.
*/

/* 
  Sketch generated by the Arduino IoT Cloud Thing "Demo"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  CloudAcceleration accelX;
  CloudAcceleration accelY;
  CloudAcceleration accelZ;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Wire.h>
#include <SparkFun_BMA400_Arduino_Library.h>

BMA400 myBMA400Sensor;

// BMA400 initialization
uint8_t bma400I2CAddress = BMA400_I2C_ADDRESS_DEFAULT; // 0x14

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(115200);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
  
  Wire.begin();
  
  // BMA400 Begin
  if (myBMA400Sensor.beginI2C(bma400I2CAddress) != BMA400_OK)
  {
    Serial.println(F("The BMA400 did not respond. Please check wiring. Spinning..."));
    while(1);
  }
  
}

void loop() {
  ArduinoCloud.update();
  // Your code here
  // BMA400 Update
  myBMA400Sensor.getSensorData();
  accelX = myBMA400Sensor.data.accelX;
  accelY = myBMA400Sensor.data.accelY;
  accelZ = myBMA400Sensor.data.accelZ;
  
}
